#!/usr/bin/bash
SCRIPT_DIR=$( cd "$( dirname "$( readlink -f "$0" )" )" && pwd -P);
PARENT_DIR=$( dirname "$SCRIPT_DIR" );
UNIX_PATH=${PARENT_DIR//\\/\/};
source "$UNIX_PATH/scripts/utils.sh";

load_configuration

BRANCH=$( current_branch_name | parse_issues )

if [[ $BRANCH =~ $SHELL_PATTERN ]]; then
    case ":$2" in
        :|:message|:template)
            echo -n "${BRANCH}: " > "$1.tmp"
            cat "$1" >> "$1.tmp"
            mv "$1.tmp" "$1"
            ;;
        *) ;;
    esac
fi
