#!/usr/bin/bash
SCRIPT_DIR=$( dirname "$(readlink -f "$0")" );
PARENT_DIR=$( dirname "$SCRIPT_DIR" );
UNIX_PATH=${PARENT_DIR//\\/\/};
source "$PARENT_DIR/scripts/utils.sh";

load_configuration

BRANCH=$( current_branch_name | parse_issues )

if [[ $BRANCH =~ $SHELL_PATTERN ]]; then
    case ":$2" in
        :|:message|:template)
#            ex -s "$1" << EOF
#0a
#${BRANCH} :
#.
#$
#w
#EOF
            echo -n "${BRANCH}: " > "$1.tmp"
            cat "$1" >> "$1.tmp"
            mv "$1.tmp" "$1"
            ;;
        *) ;;
    esac
fi
