#!/usr/bin/bash
SCRIPT_DIR=$( cd "$( dirname "$( readlink -f "$0" )" )" && pwd -P);
PARENT_DIR=$( dirname "$SCRIPT_DIR" );
UNIX_PATH=${PARENT_DIR//\\/\/};
source "$UNIX_PATH/scripts/utils.sh";

load_configuration

BRANCH_ISSUE=$( current_branch_name | parse_issues )

if [[ $BRANCH_ISSUE =~ $SHELL_PATTERN ]]; then
    case ":$2" in
        :|:message|:template)
            cat "$1" | parse_issues | grep "$BRANCH_ISSUE" >/dev/null
            if [[ "$?" -ne 0 ]]; then
                echo -n "${BRANCH_ISSUE}: " > "$1.tmp"
                cat "$1" >> "$1.tmp"
                mv "$1.tmp" "$1"
            fi
            ;;
        *) ;;
    esac
fi
