#!/bin/bash
lines="25";

# rofi
cmd="$(command -v rofi)";
options="-dmenu -lines $lines";

if [[ -z "$cmd" ]]; then
    # dmenu if rofi not found
    cmd="$(command -v dmenu)";
    options="-i -l $lines"
fi

if [[ -z "$cmd" ]]; then
    echo;
    echo "   rofi or dmenu required";
    echo;
    exit 1;
fi

b="$(git branch | $cmd $options | sed 's/[ *]//g')"; [[ -n "$b" ]] && git checkout "$b";
