#!/usr/bin/bash
SCRIPT_DIR=$( cd "$( dirname "$( readlink -f "$0" )" )" && pwd -P);
PARENT_DIR=$( dirname "$SCRIPT_DIR" );
UNIX_PATH=${PARENT_DIR//\\/\/};
source "$UNIX_PATH/scripts/utils.sh";

load_configuration

URL=$( echo "$URL" | sed 's|/$||');
git log --grep="$GREP_PATTERN"  "$@" | parse_issues | xargs -n1 -I{} echo "$URL/browse/{}"
