#!/usr/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
PARENT_DIR=$( dirname "$SCRIPT_DIR" );
UNIX_PATH=${PARENT_DIR//\\/\/};
source "$UNIX_PATH/scripts/utils.sh";

load_configuration

git log --grep="$GREP_PATTERN"  "$@" | parse_issues
